name: Test deployment

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: [opened, edited, synchronize, reopened]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Install Antora and dependencies
        run: make environment
      - name: Generate Site - Product
        run: |
          mkdir -p tmp
          bin/switch-prod-comm product
          npx antora --stacktrace \
            --log-format=pretty \
            --log-level=info \
            --log-failure-level=warn \
            turtles-local-product-playbook.yml 2>&1 | tee tmp/local-product-build.log 2>&1
            BUILD_STATUS=${PIPESTATUS[0]}
            if grep "INFO (asciidoctor)" tmp/local-product-build.log; then
              BUILD_STATUS=1
            fi
            echo "BUILD_STATUS=$BUILD_STATUS" >> $GITHUB_ENV
      - name: Check for build errors - Product
        run: |
          echo ${{ env.BUILD_STATUS }}
          if [ ${{ env.BUILD_STATUS }} -eq "0" ]; then
            exit 0
          else
            cat tmp/local-product-build.log
            exit 1
          fi
      - name: Generate Site - Community
        run: |
          mkdir -p tmp
          bin/switch-prod-comm community
          npx antora --stacktrace \
            --log-format=pretty \
            --log-level=info \
            --log-failure-level=warn \
            turtles-local-community-playbook.yml 2>&1 | tee tmp/local-community-build.log 2>&1
            BUILD_STATUS=${PIPESTATUS[0]}
            if grep "INFO (asciidoctor)" tmp/local-community-build.log; then
              BUILD_STATUS=1
            fi
            echo "BUILD_STATUS=$BUILD_STATUS" >> $GITHUB_ENV
      - name: Check for build errors - Community
        run: |
          echo ${{ env.BUILD_STATUS }}
          if [ ${{ env.BUILD_STATUS }} -eq "0" ]; then
            exit 0
          else
            cat tmp/local-community-build.log
            exit 1
          fi